### ISSUE TITLE
query against table without access kills the fdw

### ISSUE THREAD

**Issue by gettes** [mfenniak/dynamodb_fdw#13]
Hi - Thank you so much for this FDW.  It all seems to work well.  If I define a query against a table for which the access rights are not sufficient - the fdw essentially hangs and no future operation works until i restart postgresql.  Are you interested in addressing this issue (i can provide the error log from postgres 15).  I ask because it's been a few years since you have done any work on this FDW.  Again, thank you for your work.

**Comment by mfenniak** [comment]
Hey @gettes!  Thanks for the issue report -- it's been quite a few years since I've touched this project, but it is a fun one that I wouldn't mind diving into and revising.  Can you provide some more details on the steps to reproduce this, as well as the error log that you mentioned?

I won't promise anything, but it sounds like a fun issue to address.

**Comment by mfenniak** [comment]
I luckily found a problem that exactly matched the described issue when attempting to set up a development environment... but I'll need to do some rework of the docker container creation to modernize it, in order to release a new version of this. :-)
