### ISSUE TITLE
delete broken

### ISSUE THREAD

**Issue by gettes** [mfenniak/dynamodb_fdw#14]
also, delete is broken.  tried to do a simple "delete from table where pkey = '5'
and the error is:
SQL Error [XX000]: ERROR: Error in python: JSONDecodeError
  Detail: Expecting value: line 1 column 1 (char 0)

**Comment by mfenniak** [comment]
Hey @gettes!  Ditto here as with #13 -- could you provide more info, like the schema that you created that ran into this error?  This one seems like it might be a caused by poor documentation on the requirements to support modifications... but... I'm not totally sure without some more details. :-)

**Comment by gettes** [comment]
Hi @mfenniak!  I am so happy you are still interested in maintaining this FDW.   I am using it against multicorn2 (dunno if that's an issue).

CREATE FOREIGN TABLE public.ddb_spii (
	"oid" text NULL,
	partition_key text OPTIONS(mapped_attr 'partition_key', partition_key 'true') NULL,
	sort_key text OPTIONS(mapped_attr 'sort_key', sort_key 'true') NULL,
	"document" json OPTIONS(ddb_document 'true') NULL
)
SERVER mc_dynamo
OPTIONS (aws_region 'us-west-2', parallel_scan_count '8', table_name 'dev_ddb_spii');

and then...

INSERT INTO ddb_spii  (partition_key, sort_key, document)
   SELECT
     'dev2' || s,
     'dev2X' || s,
     json_build_object('text', 'hello ' || s, 'foo', 'bar','created',now())
   FROM generate_series(1, 9) s RETURNING partition_key, sort_key, document;

and then...

delete from ddb_spii where document->>'partition_key' = 'dev25';

**Comment by mfenniak** [comment]
@gettes I think this is a multicorn2 issue.  When the `delete` method on the FDW is being invoked, the arguments passed from multicorn to the FDW's delete method are just a single argument "?".

https://github.com/mfenniak/dynamodb_fdw/blob/9bc5cc49ebeb60d993a967f99cee57f638be409a/dynamodbfdw/dynamodbfdw.py#L733

I experimentally threw a `raise Exception("delete oid=%r, args=%r, kwarsg=%r" % (oid, args, kwargs))` into there, and:

```
postgres=# delete from ddb_usw2.fdwtest3 where document->>'TenantId' = 'urn:tenant:10';
ERROR:  Error in python: Exception
DETAIL:  delete oid='?', args=(), kwarsg={}
```

There's nothing relevant being passed in for the FDW.  It used to be receiving the value of the `rowid_column` from the FDW.  I would guess that the root cause is probably the same as https://github.com/pgsql-io/multicorn2/issues/15; PG14+ support in multicorn2 is a little experimental.

I'll leave this issue open, but I don't think that the fix will originate in this project.

**Comment by mfenniak** [comment]
Should be fixed by 2d86c2703af1b4bab1e85c34664b67fc4c33370b, if you're using the docker container built by this project.  I've advanced patched https://github.com/pgsql-io/multicorn2/pull/41 into this repo.

The built container for this project `ghcr.io/mfenniak/dynamodb_fdw:latest` is up-to-date with this change in version 88, so I'm going to close the issue, but there's probably follow-up to be done if the multicorn2 PR is merged.

**Comment by gettes** [comment]
It looks like they merged your PR for multicorn2 and i am trying to build against it (multcorn2 = 2.5) and I don't seem to be picking up the change.  Hmmm.

# Install Multicorn
ARG MCVER=2.5
...
        && wget https://github.com/pgsql-io/multicorn2/archive/refs/tags/v$MCVER.tar.gz \
        && tar -xvf v$MCVER.tar.gz \
        && cd multicorn2-$MCVER \
        && make \
        && make install \

**Comment by mfenniak** [comment]
I think multicorn would need to release a new version for that to work.  Version "v2.5" is the version released Sep 24 2023.

**Comment by gettes** [comment]
Hi @mfenniak - Just wanted to let you know I was able to build the latest multicorn2 and I can confirm delete works.

THANK YOU SO MUCH for all your help!
