### ISSUE TITLE
how to store binary data?

### ISSUE THREAD

**Issue by gettes** [mfenniak/dynamodb_fdw#19]
Hi @mfenniak -- it is unclear to me how I can store binary data?  Either with JSON or just a primary key and a single field (document?) of binary?

**Comment by gettes** [comment]
Does this help?
https://stackoverflow.com/questions/21478086/how-to-store-binary-data-in-dynamo-with-boto

**Comment by mfenniak** [comment]
Basically dynamodb_fdw takes the json object in the document field, does a `json.loads` on it...

https://github.com/mfenniak/dynamodb_fdw/blob/83be9af89d08bb2ae18a1e7670965656c3014c15/dynamodbfdw/dynamodbfdw.py#L748

And sends it over to the boto3 table batch writer...

https://github.com/mfenniak/dynamodb_fdw/blob/83be9af89d08bb2ae18a1e7670965656c3014c15/dynamodbfdw/dynamodbfdw.py#L789-L797

Which can hypothetically support the `Item` field containing a map between a string, and another string, a number, a bytes object, a boolean, None, a set of strings, a set of numbers, a set of bytes, an empty array, or any other hash (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/table/put_item.html)

So I don't think there would be a path to get binary data through because `json.loads` will never return binary data, and there isn't standardized way to mark binary data in JSON, and other than GSI and LSIs dynamodb_fdw doesn't do any other document modification.

I could imagine a few different paths to implementing...

### JSON Based

"Mark" fields in a json document in some way that they are binary, and use a custom json decoder to decode them into bytes when the marking is identified.  For example, this could be `{"field": "\x1234"}`, or something.
  
This seems the most ugly approach to use as you'd probably have `bytea` data in PG, which you'd have to encode into JSON, just to decode an instant later.  And you'd have risk that the automatic detection would falsely identify data.

### `bytea` Columns

Add to the `insert` method the ability to use columns that are marked as `mapped_attr`, and translate them from PG columns into fields in the DDB item.  Currently the columns are only used if they're marked as the `ddb_document` (json) column, or a GSI or LSI.  This would be a nice general improvement -- if you wanted to fully create a schema in PG to represent the DDB table, rather than just putting things into a JSON doc, this would make the whole insert work correctly, where it kinda silently drops data today.

Then, support/test that columns that are of a type `bytea` work correctly.  That might be entirely automatic if multicorn all that, which the code over there seems to support.
  
The downside to this option is that foreign schema import can't possibly detect fields in the document, so schema management has to be done manually.

---

The second option seems like it would make more sense in general.

I'm hacking around on these projects in my spare time for fun, and this sounds interesting, but I won't be able to hop on this immediately... so for right now, I think it's not possible as-is.  But I'd be happy to review a PR if you want to take a stab at it.  My advice would be to first use a manual schema creation to test if binary **read** into a column works... if it does, that would mean that there will be no blockers on the multicorn side, and the only changes required should be some straightforward dict updates in the `insert()` function to copy data around to the right place.

**Comment by gettes** [comment]
Conceptually, I understand what you are describing for the bytea columns.  I have been looking at the code and what to change is a bit beyond my reach.  I am not a python programmer... but, if there is some chance of you providing me a starting point... i'd be willing to whack at it further.  Any help is appreciated.  Thank you so much for all you do!

**Comment by mfenniak** [comment]
@gettes This seems like it's on the right track... but when `bytea` data type is written in the integration test through PG, it doesn't get received as a `bytes` object in the `insert()` method.  It might not be working correctly in multicorn?  I'm not sure yet; will probably be able to look into this more later in the week.

https://github.com/mfenniak/dynamodb_fdw/compare/binary-column-insert

**Comment by mfenniak** [comment]
I fixed up the issues in that branch and opened #20 -- other than the fact that you need to define the schema a little more specifically, it allows you to interact with a binary field as if it were bytea data in Postgres.

Example of defining a schema -- the "test_text_field" and "test_bytea_fields" are mapped to specific DynamoDB item attributes:

https://github.com/mfenniak/dynamodb_fdw/pull/20/files#diff-369c8dad76dd575ac7b734df19cf4b02eddf6aeebf39e5c39991f24cdb07fd47R234-R243

I need to do a little cleanup on this branch before merging, but you could test it out if you're able.

**Comment by gettes** [comment]
Wow - you are truly awesome!  I have been traveling a bit today.  I will test this out either later tonite or tomorrow morning (I am USA Eastern TZ).  THANK YOU!  THANK YOU!  THANK YOU!

**Comment by gettes** [comment]
I tried to insert an image: 
insert into ddb_img1 (pkey, img)
	select id, image  from public.img1;
and I am getting
SQL Error [XX000]: ERROR: Error in python: TypeError
  Detail: Input string must be text, not bytes
 
image is binary (bytea) in PG.

**Comment by gettes** [comment]
ok, i don't think i built things properly.  i will wait for you to properly cleanup and merge.  thanks again!

**Comment by mfenniak** [comment]
@gettes  All the related changes are merged, just so you know.  Let me know if you have any problems and I can try to help out.
